import { createCrudService } from "./createCrudService";

export const HEADPHONE_YEARS = ["2022", "2023", "2024", "2025", "2026"];

export const HEADPHONE_STATUSES = [
  { value: "IN USE", badge: "good" },
  { value: "IN STORE", badge: "store" },
  { value: "NULL", badge: "null" },
  { value: "BROKEN", badge: "broken" },
];

export const defaultHeadphoneAssets = [
  {
    id: 1,
    entityId: "HP-Site-23001",
    serialNumber: "7910808128501",
    manufactur: "MICROSOFT LifeChat LX-300",
    type: "MID",
    assignTo: "Server Room",
    dept: "MID",
    pcName: "TEL-PC-14099",
    status: "IN USE",
    badge: "good",
    year: "2023",
    photo: "",
  },
  {
    id: 2,
    entityId: "HP-SITE-24001",
    serialNumber: "8994067060301",
    manufactur: "REXUS",
    type: "VONIX",
    assignTo: "-",
    dept: "-",
    pcName: "-",
    status: "NULL",
    badge: "null",
    year: "2024",
    photo: "",
  },
  {
    id: 3,
    entityId: "HP-Site-23002",
    serialNumber: "7910808128502",
    manufactur: "MICROSOFT LifeChat LX-300",
    type: "MID",
    assignTo: "Server Room",
    dept: "MID",
    pcName: "-",
    status: "IN STORE",
    badge: "store",
    year: "2023",
    photo: "",
  },
  {
    id: 4,
    entityId: "HP-Site-23003",
    serialNumber: "7910808128503",
    manufactur: "MICROSOFT LifeChat LX-300",
    type: "MID",
    assignTo: "Server Room",
    dept: "MID",
    pcName: "-",
    status: "IN STORE",
    badge: "store",
    year: "2023",
    photo: "",
  },
  {
    id: 5,
    entityId: "HP-SITE-24002",
    serialNumber: "8994067060302",
    manufactur: "REXUS",
    type: "VONIX",
    assignTo: "Ahmad Prasetyo",
    dept: "-",
    pcName: "-",
    status: "IN USE",
    badge: "good",
    year: "2024",
    photo: "",
  },
  {
    id: 6,
    entityId: "HP-SITE-24003",
    serialNumber: "8994067060303",
    manufactur: "REXUS",
    type: "VONIX",
    assignTo: "-",
    dept: "-",
    pcName: "-",
    status: "NULL",
    badge: "null",
    year: "2024",
    photo: "",
  },
  {
    id: 7,
    entityId: "HP-SITE-24004",
    serialNumber: "8994067060304",
    manufactur: "REXUS",
    type: "VONIX",
    assignTo: "-",
    dept: "-",
    pcName: "-",
    status: "NULL",
    badge: "null",
    year: "2024",
    photo: "",
  },
];

// TODO: BACKEND - resource path final di backend, contoh: GET/POST /headphone-assets
export const headphoneAssetService = createCrudService(
  "headphoneAssets",
  defaultHeadphoneAssets
);
